### ISSUE TITLE
Complete properly first command

### ISSUE THREAD

**Issue by jrecuero** [jrecuero/go-cli#28]
There is an exception when first command is being enter manually:
Please select:
>>> panic: runtime error: index out of range

goroutine 1 [running]:
github.com/jrecuero/go-cli/syntax.(*Matcher).Complete(0xc4200f1b98, 0x115bce0, 0xc4201866b0, 0xc4201866b0, 0xc4201a00c4, 0x1)
	/Users/jorecuer/Repository/go/src/github.com/jrecuero/go-cli/syntax/matcher.go:127 +0xaeb
github.com/jrecuero/go-cli/prompter.(*Prompter).completer(0xc42000a380, 0xc4201a00c3, 0x1, 0x1, 0x0, 0x128c560, 0x119899f)
	/Users/jorecuer/Repository/go/src/github.com/jrecuero/go-cli/prompter/prompter.go:44 +0x13c
github.com/jrecuero/go-cli/prompter.(*Prompter).(github.com/jrecuero/go-cli/prompter.completer)-fm(0xc4201a00c3, 0x1, 0x1, 0x1172960, 0x128c501, 0xc4201ac1c0)
	/Users/jorecuer/Repository/go/src/github.com/jrecuero/go-cli/prompter/prompter.go:81 +0x48
github.com/jrecuero/go-cli/vendor/github.com/c-bata/go-prompt.(*CompletionManager).Update(0xc420096460, 0xc4201a00c3, 0x1, 0x1)
	/Users/jorecuer/Repository/go/src/github.com/jrecuero/go-cli/vendor/github.com/c-bata/go-prompt/completion.go:68 +0x48
github.com/jrecuero/go-cli/vendor/github.com/c-bata/go-prompt.(*Prompt).Run(0xc4200e4280)
	/Users/jorecuer/Repository/go/src/github.com/jrecuero/go-cli/vendor/github.com/c-bata/go-prompt/prompt.go:91 +0x55a
github.com/jrecuero/go-cli/prompter.(*Prompter).Run(0xc42000a380)
	/Users/jorecuer/Repository/go/src/github.com/jrecuero/go-cli/prompter/prompter.go:91 +0x2de
main.runPrompter()
	/Users/jorecuer/Repository/go/src/github.com/jrecuero/go-cli/app/cli/prompt/main.go:130 +0x8e
main.main()
	/Users/jorecuer/Repository/go/src/github.com/jrecuero/go-cli/app/cli/prompt/main.go:137 +0x20
exit status 2

**Comment by jrecuero** [comment]
First command is executed now properly.
